try {
    const n = 1
    const m = n + z
    console.log(m);
} catch(err) {
    console.log(err.name)
}